In [1]:
import pandas as pd

df = pd.read_csv("/home/caoli/marketing-analytics-platform/churn-analysis/data/fact_events.csv")

In [2]:
df.columns

Index(['user_id', 'product_id', 'event_type', 'time_id', 'price'], dtype='str')

In [3]:
df.head()

     user_id  product_id event_type  time_id    price
0  541312140    44600062       view        0    35.79
1  554748717     3900821       view        0    33.20
2  519107250    17200506       view        2   543.10
3  550050854     1307067       view        2   251.74
4  535871217     1004237       view        4  1081.98

In [4]:
df['time_id']

0            0
1            0
2            2
3            2
4            4
         ...
99995    99987
99996    99987
99997    99987
99998    99987
99999    99987
Name: time_id, Length: 100000, dtype: int64

In [5]:
df.info

<bound method DataFrame.info of          user_id  product_id event_type  time_id    price
0      541312140    44600062       view        0    35.79
1      554748717     3900821       view        0    33.20
2      519107250    17200506       view        2   543.10
3      550050854     1307067       view        2   251.74
4      535871217     1004237       view        4  1081.98
...          ...         ...        ...      ...      ...
99995  515593818    17300136       view    99987   102.96
99996  530821477     2601810       view    99987   155.29
99997  521314335     1306100       view    99987  1029.60
99998  555131253     3200549       view    99987    25.71
99999  523211916     6200949       view    99987    10.17

[100000 rows x 5 columns]>

In [6]:
purchases = df[df['event_type'] == 'purchase']

In [7]:
last_purchase = purchases.groupby('user_id')['time_id'].max()

In [8]:
reference_time = df['time_id'].max()

In [9]:
last_purchase = purchases.groupby('user_id')['time_id'].max()
reference_time = df['time_id'].max()

In [10]:
churn_threshold = 30  # você pode ajustar

churn = (reference_time - last_purchase) > churn_threshold

In [11]:
user_df = df.groupby('user_id').agg({
    'price': 'mean',
    'event_type': 'count'
}).rename(columns={
    'price': 'avg_price',
    'event_type': 'total_events'
})

In [12]:
user_df['last_purchase'] = last_purchase
user_df['churn'] = churn

In [13]:
user_df['churn'].mean()

np.float64(0.9985029940119761)

In [14]:
user_df.groupby('churn').mean()

        avg_price  total_events  last_purchase
churn
False  105.725333      8.500000   99963.000000
True   295.783749      8.685907   54090.996252

In [15]:
first_event = df.groupby('user_id')['time_id'].min()
lifetime = last_purchase - first_event

user_df['lifetime'] = lifetime

In [17]:
import sklearn

ModuleNotFoundError: No module named 'sklearn'

In [19]:
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier

X = user_df[['avg_price', 'total_events', 'lifetime']].fillna(0)
y = user_df['churn']

X_train, X_test, y_train, y_test = train_test_split(X, y)

model = RandomForestClassifier()
model.fit(X_train, y_train)

model.score(X_test, y_test)

ModuleNotFoundError: No module named 'sklearn'

In [ ]:
import sys
!{sys.executable} -m pip install scikit-learn

/home/caoli/.venv/bin/python: No module named pip